# Generated by Django 2.1.15 on 2020-01-22 01:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the house.', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Light',
            fields=[
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', help_text='Current state of the light.', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('current_temperature', models.DecimalField(decimal_places=2, help_text='Current temperature at the thermostat.', max_digits=5)),
                ('house', models.ForeignKey(help_text='Related house.', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homes.House')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thermostat',
            fields=[
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('off', 'Off'), ('fan', 'Fan'), ('auto', 'Auto'), ('cool', 'Cool'), ('heat', 'Heat')], default='off', help_text='Current mode of the thermostat.', max_length=5)),
                ('current_temperature', models.DecimalField(decimal_places=2, help_text='Current temperature at the thermostat.', max_digits=5)),
                ('temperature_set_point', models.DecimalField(decimal_places=2, help_text='Temperature set point.', max_digits=5)),
                ('house', models.ForeignKey(help_text='Related house.', on_delete=django.db.models.deletion.CASCADE, related_name='thermostats', to='homes.House')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='light',
            name='room',
            field=models.ForeignKey(help_text='Related room.', on_delete=django.db.models.deletion.CASCADE, related_name='lights', to='homes.Room'),
        ),
    ]
