# Generated by Django 2.1.15 on 2020-01-22 02:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightStateChangeInformation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('previous_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('next_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('light', models.ForeignKey(help_text='Light Change Information', on_delete=django.db.models.deletion.CASCADE, related_name='lights', to='homes.Light')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomStateChangeInformation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('previous_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('next_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('room', models.ForeignKey(help_text='Room State Change Information', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homes.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThermostatStateChangeInformation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID', primary_key=True, serialize=False)),
                ('previous_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('next_state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('thermostat', models.ForeignKey(help_text='Thermostat State Change Information', on_delete=django.db.models.deletion.CASCADE, related_name='thermostats', to='homes.Thermostat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
